"""Donnees de reference des origines (departements, DOM-TOM, pays), partagees entre tous les festivals."""
from checkin.models import Origin

GROUPE_01_19 = "01–19"
GROUPE_2A_39 = "2A/2B, 21–39"
GROUPE_40_59 = "40–59"
GROUPE_60_79 = "60–79"
GROUPE_80_95 = "80–95"
GROUPE_DOM_TOM = "DOM-TOM"
GROUPE_ETRANGER = "Étranger"

# (code, nom, type, groupe)
_ORIGINS_DATA = [
    ("01", "Ain", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("02", "Aisne", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("03", "Allier", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("04", "Alpes-de-Haute-Provence", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("05", "Hautes-Alpes", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("06", "Alpes-Maritimes", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("07", "Ardèche", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("08", "Ardennes", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("09", "Ariège", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("10", "Aube", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("11", "Aude", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("12", "Aveyron", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("13", "Bouches-du-Rhône", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("14", "Calvados", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("15", "Cantal", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("16", "Charente", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("17", "Charente-Maritime", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("18", "Cher", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("19", "Corrèze", Origin.TYPE_DEPARTEMENT, GROUPE_01_19),
    ("2A", "Corse-du-Sud", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("2B", "Haute-Corse", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("21", "Côte-d'Or", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("22", "Côtes-d'Armor", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("23", "Creuse", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("24", "Dordogne", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("25", "Doubs", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("26", "Drôme", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("27", "Eure", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("28", "Eure-et-Loir", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("29", "Finistère", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("30", "Gard", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("31", "Haute-Garonne", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("32", "Gers", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("33", "Gironde", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("34", "Hérault", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("35", "Ille-et-Vilaine", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("36", "Indre", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("37", "Indre-et-Loire", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("38", "Isère", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("39", "Jura", Origin.TYPE_DEPARTEMENT, GROUPE_2A_39),
    ("40", "Landes", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("41", "Loir-et-Cher", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("42", "Loire", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("43", "Haute-Loire", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("44", "Loire-Atlantique", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("45", "Loiret", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("46", "Lot", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("47", "Lot-et-Garonne", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("48", "Lozère", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("49", "Maine-et-Loire", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("50", "Manche", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("51", "Marne", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("52", "Haute-Marne", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("53", "Mayenne", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("54", "Meurthe-et-Moselle", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("55", "Meuse", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("56", "Morbihan", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("57", "Moselle", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("58", "Nièvre", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("59", "Nord", Origin.TYPE_DEPARTEMENT, GROUPE_40_59),
    ("60", "Oise", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("61", "Orne", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("62", "Pas-de-Calais", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("63", "Puy-de-Dôme", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("64", "Pyrénées-Atlantiques", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("65", "Hautes-Pyrénées", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("66", "Pyrénées-Orientales", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("67", "Bas-Rhin", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("68", "Haut-Rhin", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("69", "Rhône", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("70", "Haute-Saône", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("71", "Saône-et-Loire", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("72", "Sarthe", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("73", "Savoie", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("74", "Haute-Savoie", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("75", "Paris", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("76", "Seine-Maritime", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("77", "Seine-et-Marne", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("78", "Yvelines", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("79", "Deux-Sèvres", Origin.TYPE_DEPARTEMENT, GROUPE_60_79),
    ("80", "Somme", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("81", "Tarn", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("82", "Tarn-et-Garonne", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("83", "Var", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("84", "Vaucluse", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("85", "Vendée", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("86", "Vienne", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("87", "Haute-Vienne", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("88", "Vosges", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("89", "Yonne", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("90", "Territoire de Belfort", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("91", "Essonne", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("92", "Hauts-de-Seine", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("93", "Seine-Saint-Denis", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("94", "Val-de-Marne", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("95", "Val-d'Oise", Origin.TYPE_DEPARTEMENT, GROUPE_80_95),
    ("971", "Guadeloupe", Origin.TYPE_DOM_TOM, GROUPE_DOM_TOM),
    ("972", "Martinique", Origin.TYPE_DOM_TOM, GROUPE_DOM_TOM),
    ("973", "Guyane", Origin.TYPE_DOM_TOM, GROUPE_DOM_TOM),
    ("974", "La Réunion", Origin.TYPE_DOM_TOM, GROUPE_DOM_TOM),
    ("976", "Mayotte", Origin.TYPE_DOM_TOM, GROUPE_DOM_TOM),
    ("BE", "Belgique", Origin.TYPE_PAYS, GROUPE_ETRANGER),
    ("CH", "Suisse", Origin.TYPE_PAYS, GROUPE_ETRANGER),
    ("DE", "Allemagne", Origin.TYPE_PAYS, GROUPE_ETRANGER),
    ("IT", "Italie", Origin.TYPE_PAYS, GROUPE_ETRANGER),
    ("ES", "Espagne", Origin.TYPE_PAYS, GROUPE_ETRANGER),
    ("LU", "Luxembourg", Origin.TYPE_PAYS, GROUPE_ETRANGER),
    ("NL", "Pays-Bas", Origin.TYPE_PAYS, GROUPE_ETRANGER),
    ("GB", "Royaume-Uni", Origin.TYPE_PAYS, GROUPE_ETRANGER),
    ("PT", "Portugal", Origin.TYPE_PAYS, GROUPE_ETRANGER),
    ("MC", "Monaco", Origin.TYPE_PAYS, GROUPE_ETRANGER),
    ("AUTRE", "Autre pays", Origin.TYPE_AUTRE, GROUPE_ETRANGER),
]

ORIGINS = [
    {"code": code, "nom": nom, "type": type_, "groupe": groupe, "ordre_affichage": index}
    for index, (code, nom, type_, groupe) in enumerate(_ORIGINS_DATA, start=1)
]
