# Generated by Django 6.1.1 on 2026-09-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='checkin.festival')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
