# Generated by Django 6.1.1 on 2026-09-15 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_edition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('organisateur', 'Organisateur'), ('benevole', 'Bénévole')], max_length=20)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='checkin.festival')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'festival'), name='unique_membership_per_user_festival')],
            },
        ),
    ]
