# Generated by Django 6.1.1 on 2026-09-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('departement', 'Département'), ('dom_tom', 'DOM-TOM'), ('pays', 'Pays'), ('autre', 'Autre')], max_length=20)),
                ('groupe', models.CharField(max_length=50)),
                ('ordre_affichage', models.IntegerField()),
            ],
            options={
                'ordering': ['ordre_affichage'],
            },
        ),
    ]
